/**
 * Types for WXCODE Project Progress Dashboard
 *
 * Dashboard data is generated by /wxcode:* skills and stored
 * in .planning/dashboard.json within the output project workspace.
 */

/** Project metadata */
export interface DashboardProject {
  name: string;
  core_value: string;
  current_milestone: string;
  description: string;
}

/** Current execution position */
export interface DashboardPosition {
  milestone: string;
  phase_number: number;
  phase_name: string;
  phase_total: number;
  plan_number: number;
  plan_total: number;
  status: "pending" | "in_progress" | "complete" | "blocked";
}

/** Overall progress metrics */
export interface DashboardProgress {
  phases_complete: number;
  phases_total: number;
  phases_percentage: number;
  requirements_complete: number;
  requirements_total: number;
  requirements_percentage: number;
}

/** Plan within a phase */
export interface DashboardPlan {
  number: number;
  name: string;
  status: "pending" | "in_progress" | "complete" | "blocked";
  tasks_complete: number;
  tasks_total: number;
  summary: string | null;
}

/** Phase in the roadmap */
export interface DashboardPhase {
  number: number;
  name: string;
  goal: string;
  status: "pending" | "in_progress" | "complete" | "blocked";
  requirements_covered: string[];
  plans: DashboardPlan[];
}

/** Requirement item */
export interface DashboardRequirementItem {
  id: string;
  description: string;
  complete: boolean;
  phase: number | null;
}

/** Requirement category */
export interface DashboardRequirementCategory {
  id: string;
  name: string;
  complete: number;
  total: number;
  percentage: number;
  items: DashboardRequirementItem[];
}

/** Requirements summary */
export interface DashboardRequirements {
  total: number;
  complete: number;
  categories: DashboardRequirementCategory[];
}

/** Todo item */
export interface DashboardTodo {
  id: string;
  subject: string;
  status: "pending" | "in_progress" | "complete";
  priority: "low" | "medium" | "high";
}

/** Conversion project info */
export interface DashboardConversion {
  is_conversion_project: boolean;
  elements_converted: number;
  elements_total: number;
  stack: string;
}

/** Dashboard metadata */
export interface DashboardMeta {
  generated_at: string;
  wxcode_version: string;
}

/** Complete dashboard data structure */
export interface DashboardData {
  project: DashboardProject;
  current_position: DashboardPosition;
  progress: DashboardProgress;
  phases: DashboardPhase[];
  requirements: DashboardRequirements;
  blockers: string[];
  todos: DashboardTodo[];
  milestones_history: unknown[];
  conversion: DashboardConversion;
  meta: DashboardMeta;
}
