"""Preview server for converted pages.

Simple FastAPI server to preview converted pages from MongoDB.
"""

from contextlib import asynccontextmanager
from pathlib import Path
from tempfile import mkdtemp

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pymongo import MongoClient
import uvicorn


# MongoDB connection
MONGO_URI = "mongodb://localhost:27017"
DATABASE = "wxcode"

# Temp directory for templates
TEMP_DIR = Path(mkdtemp(prefix="wxcode_preview_"))
TEMPLATES_DIR = TEMP_DIR / "templates"
STATIC_DIR = TEMP_DIR / "static"


def setup_directories():
    """Create directories."""
    TEMPLATES_DIR.mkdir(exist_ok=True)
    (TEMPLATES_DIR / "pages").mkdir(exist_ok=True)
    STATIC_DIR.mkdir(exist_ok=True)
    (STATIC_DIR / "css").mkdir(exist_ok=True)
    (STATIC_DIR / "js").mkdir(exist_ok=True)


def load_templates_from_mongo():
    """Load converted templates from MongoDB."""
    client = MongoClient(MONGO_URI)
    db = client[DATABASE]

    cursor = db.elements.find({
        "conversion.status": "converted",
        "conversion.target_files": {"$exists": True}
    })

    for element in cursor:
        for target_file in element.get("conversion", {}).get("target_files", []):
            file_path = target_file.get("path", "")
            content = target_file.get("content", "")

            if "templates/" in file_path and content:
                rel_path = file_path.split("templates/")[-1]
                full_path = TEMPLATES_DIR / rel_path
                full_path.parent.mkdir(parents=True, exist_ok=True)
                full_path.write_text(content)
                print(f"  Loaded template: {rel_path}")

    client.close()


def create_base_template():
    """Create base template."""
    base_html = '''<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Application{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    <link rel="stylesheet" href="/static/css/app.css">
    {% block head_extra %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="/">Application</a>
        </div>
    </nav>

    <main class="container mt-4">
        {% block content %}{% endblock %}
    </main>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container text-center text-muted">
            <span>&copy; 2024 - Generated by wxcode</span>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/app.js"></script>
    {% block scripts_extra %}{% endblock %}
</body>
</html>'''
    (TEMPLATES_DIR / "base.html").write_text(base_html)


def create_static_files():
    """Create static CSS/JS files."""
    css = '''/* Preview styles */
.page-container { padding: 1rem 0; }
.control-container { margin-bottom: 1rem; }
.control-edit, .control-combo { margin-bottom: 1rem; }
.control-static { display: block; margin-bottom: 0.5rem; }
.control-image { max-width: 200px; height: auto; }
'''
    (STATIC_DIR / "css" / "app.css").write_text(css)

    js = '''// Preview scripts
document.addEventListener('DOMContentLoaded', function() {
    console.log('Preview loaded');
});
'''
    (STATIC_DIR / "js" / "app.js").write_text(js)


# Setup on module load
print("Setting up preview server...")
setup_directories()
create_base_template()
create_static_files()
load_templates_from_mongo()
print(f"Templates loaded to: {TEMPLATES_DIR}")

# Create app
app = FastAPI(title="WXCODE Preview")

# Mount static files
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

# Templates
templates = Jinja2Templates(directory=str(TEMPLATES_DIR))


@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    """List available pages."""
    pages_dir = TEMPLATES_DIR / "pages"
    pages = [f.stem for f in pages_dir.glob("*.html")] if pages_dir.exists() else []

    html = "<h1>Available Pages</h1><ul>"
    for page in pages:
        html += f'<li><a href="/page/{page}">{page}</a></li>'
    html += "</ul>"
    return HTMLResponse(html)


@app.get("/page/{page_name}", response_class=HTMLResponse)
async def render_page(request: Request, page_name: str):
    """Render a converted page."""
    return templates.TemplateResponse(
        f"pages/{page_name}.html",
        {
            "request": request,
            "page_title": page_name.replace("_", " ").title(),
            "page_name": page_name,
        }
    )


def run_server(host: str = "0.0.0.0", port: int = 8080):
    """Run the preview server."""
    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    run_server()
